// Comprehensive list of NSE-listed stocks (NIFTY 500 + popular mid/small caps)
// Used as a local search index to supplement Yahoo Finance search API,
// which has incomplete coverage of Indian stocks.

export interface NSEStockEntry {
    symbol: string   // Yahoo Finance symbol (e.g. "RELIANCE.NS")
    name: string     // Company name for display and search matching
}

export const NSE_STOCKS: NSEStockEntry[] = [
    // ── NIFTY 50 ──────────────────────────────────────────────────
    { symbol: 'RELIANCE.NS', name: 'Reliance Industries' },
    { symbol: 'TCS.NS', name: 'Tata Consultancy Services' },
    { symbol: 'HDFCBANK.NS', name: 'HDFC Bank' },
    { symbol: 'INFY.NS', name: 'Infosys' },
    { symbol: 'ICICIBANK.NS', name: 'ICICI Bank' },
    { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever' },
    { symbol: 'SBIN.NS', name: 'State Bank of India' },
    { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel' },
    { symbol: 'ITC.NS', name: 'ITC Limited' },
    { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank' },
    { symbol: 'LT.NS', name: 'Larsen & Toubro' },
    { symbol: 'HCLTECH.NS', name: 'HCL Technologies' },
    { symbol: 'AXISBANK.NS', name: 'Axis Bank' },
    { symbol: 'ASIANPAINT.NS', name: 'Asian Paints' },
    { symbol: 'MARUTI.NS', name: 'Maruti Suzuki' },
    { symbol: 'SUNPHARMA.NS', name: 'Sun Pharma' },
    { symbol: 'TITAN.NS', name: 'Titan Company' },
    { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance' },
    { symbol: 'WIPRO.NS', name: 'Wipro' },
    { symbol: 'TATAMOTORS.NS', name: 'Tata Motors' },
    { symbol: 'POWERGRID.NS', name: 'Power Grid Corp' },
    { symbol: 'NTPC.NS', name: 'NTPC Limited' },
    { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement' },
    { symbol: 'NESTLEIND.NS', name: 'Nestle India' },
    { symbol: 'TATASTEEL.NS', name: 'Tata Steel' },
    { symbol: 'JSWSTEEL.NS', name: 'JSW Steel' },
    { symbol: 'ADANIENT.NS', name: 'Adani Enterprises' },
    { symbol: 'TECHM.NS', name: 'Tech Mahindra' },
    { symbol: 'ONGC.NS', name: 'ONGC' },
    { symbol: 'COALINDIA.NS', name: 'Coal India' },
    { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv' },
    { symbol: 'ADANIPORTS.NS', name: 'Adani Ports' },
    { symbol: 'DRREDDY.NS', name: 'Dr Reddys Laboratories' },
    { symbol: 'CIPLA.NS', name: 'Cipla' },
    { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals' },
    { symbol: 'DIVISLAB.NS', name: 'Divis Laboratories' },
    { symbol: 'EICHERMOT.NS', name: 'Eicher Motors' },
    { symbol: 'GRASIM.NS', name: 'Grasim Industries' },
    { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp' },
    { symbol: 'HINDALCO.NS', name: 'Hindalco Industries' },
    { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank' },
    { symbol: 'M&M.NS', name: 'Mahindra & Mahindra' },
    { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance' },
    { symbol: 'BRITANNIA.NS', name: 'Britannia Industries' },
    { symbol: 'BPCL.NS', name: 'Bharat Petroleum' },
    { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance' },
    { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products' },
    { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto' },
    { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance' },
    { symbol: 'JSWENERGY.NS', name: 'JSW Energy' },

    // ── NIFTY NEXT 50 / NIFTY 100 ─────────────────────────────────
    { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy' },
    { symbol: 'ADANIPOWER.NS', name: 'Adani Power' },
    { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements' },
    { symbol: 'ATGL.NS', name: 'Adani Total Gas' },
    { symbol: 'AWL.NS', name: 'Adani Wilmar' },
    { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda' },
    { symbol: 'BEL.NS', name: 'Bharat Electronics' },
    { symbol: 'BERGEPAINT.NS', name: 'Berger Paints' },
    { symbol: 'BOSCHLTD.NS', name: 'Bosch' },
    { symbol: 'CANBK.NS', name: 'Canara Bank' },
    { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Finance' },
    { symbol: 'COLPAL.NS', name: 'Colgate Palmolive' },
    { symbol: 'DABUR.NS', name: 'Dabur India' },
    { symbol: 'DLF.NS', name: 'DLF Limited' },
    { symbol: 'DMART.NS', name: 'Avenue Supermarts DMart' },
    { symbol: 'GAIL.NS', name: 'GAIL India' },
    { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products' },
    { symbol: 'GODREJPROP.NS', name: 'Godrej Properties' },
    { symbol: 'HAVELLS.NS', name: 'Havells India' },
    { symbol: 'HAL.NS', name: 'Hindustan Aeronautics' },
    { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life' },
    { symbol: 'ICICIGI.NS', name: 'ICICI Lombard General Insurance' },
    { symbol: 'INDUSTOWER.NS', name: 'Indus Towers' },
    { symbol: 'IOC.NS', name: 'Indian Oil Corporation' },
    { symbol: 'IRCTC.NS', name: 'Indian Railway Catering & Tourism' },
    { symbol: 'IRFC.NS', name: 'Indian Railway Finance Corp' },
    { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel & Power' },
    { symbol: 'LICI.NS', name: 'Life Insurance Corporation' },
    { symbol: 'LTIM.NS', name: 'LTIMindtree' },
    { symbol: 'LTTS.NS', name: 'L&T Technology Services' },
    { symbol: 'LUPIN.NS', name: 'Lupin' },
    { symbol: 'MARICO.NS', name: 'Marico' },
    { symbol: 'MCDOWELL-N.NS', name: 'United Spirits' },
    { symbol: 'MOTHERSON.NS', name: 'Motherson Sumi Wiring' },
    { symbol: 'MPHASIS.NS', name: 'Mphasis' },
    { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance' },
    { symbol: 'NAUKRI.NS', name: 'Info Edge Naukri' },
    { symbol: 'NHPC.NS', name: 'NHPC' },
    { symbol: 'NMDC.NS', name: 'NMDC' },
    { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty' },
    { symbol: 'PEL.NS', name: 'Piramal Enterprises' },
    { symbol: 'PERSISTENT.NS', name: 'Persistent Systems' },
    { symbol: 'PETRONET.NS', name: 'Petronet LNG' },
    { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries' },
    { symbol: 'PIIND.NS', name: 'PI Industries' },
    { symbol: 'PNB.NS', name: 'Punjab National Bank' },
    { symbol: 'POLYCAB.NS', name: 'Polycab India' },
    { symbol: 'RECLTD.NS', name: 'REC Limited' },
    { symbol: 'SAIL.NS', name: 'Steel Authority of India' },
    { symbol: 'SBICARD.NS', name: 'SBI Cards' },
    { symbol: 'SIEMENS.NS', name: 'Siemens' },
    { symbol: 'SRF.NS', name: 'SRF Limited' },
    { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi' },
    { symbol: 'TATAPOWER.NS', name: 'Tata Power' },
    { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharma' },
    { symbol: 'TORNTPOWER.NS', name: 'Torrent Power' },
    { symbol: 'TRENT.NS', name: 'Trent Limited' },
    { symbol: 'UNIONBANK.NS', name: 'Union Bank of India' },
    { symbol: 'UPL.NS', name: 'UPL Limited' },
    { symbol: 'VEDL.NS', name: 'Vedanta' },
    { symbol: 'VOLTAS.NS', name: 'Voltas' },
    { symbol: 'YESBANK.NS', name: 'Yes Bank' },
    { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences' },

    // ── POPULAR MID-CAP / THEMATIC ─────────────────────────────────
    { symbol: 'ZOMATO.NS', name: 'Zomato' },
    { symbol: 'PAYTM.NS', name: 'One97 Communications Paytm' },
    { symbol: 'NYKAA.NS', name: 'FSN E-Commerce Nykaa' },
    { symbol: 'POLICYBZR.NS', name: 'PB Fintech PolicyBazaar' },
    { symbol: 'DELHIVERY.NS', name: 'Delhivery' },
    { symbol: 'CARTRADE.NS', name: 'CarTrade Tech' },
    { symbol: 'EASEMYTRIP.NS', name: 'Easy Trip Planners' },
    { symbol: 'IDEAFORGE.NS', name: 'Ideaforge Technology' },
    { symbol: 'MAPMYINDIA.NS', name: 'CE Info Systems MapMyIndia' },
    { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds Technologies' },
    { symbol: 'ROUTE.NS', name: 'Route Mobile' },
    { symbol: 'LATENTVIEW.NS', name: 'Latent View Analytics' },
    { symbol: 'STARHEALTH.NS', name: 'Star Health Insurance' },
    { symbol: 'MEDANTA.NS', name: 'Global Health Medanta' },
    { symbol: 'MAXHEALTH.NS', name: 'Max Healthcare' },
    { symbol: 'RAINBOWCR.NS', name: 'Rainbow Childrens Medicare' },
    { symbol: 'KPITTECH.NS', name: 'KPIT Technologies' },
    { symbol: 'COFORGE.NS', name: 'Coforge' },
    { symbol: 'CYIENT.NS', name: 'Cyient' },
    { symbol: 'ZENTEC.NS', name: 'Zensar Technologies' },
    { symbol: 'TATACOMM.NS', name: 'Tata Communications' },
    { symbol: 'TATACHEM.NS', name: 'Tata Chemicals' },
    { symbol: 'TVSMOTOR.NS', name: 'TVS Motor' },
    { symbol: 'BHARATFORG.NS', name: 'Bharat Forge' },
    { symbol: 'APLAPOLLO.NS', name: 'APL Apollo Tubes' },
    { symbol: 'ASTRAL.NS', name: 'Astral' },
    { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries' },
    { symbol: 'DEEPAKNI.NS', name: 'Deepak Nitrite' },
    { symbol: 'ATUL.NS', name: 'Atul Limited' },
    { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine' },
    { symbol: 'CLEAN.NS', name: 'Clean Science and Technology' },
    { symbol: 'SOLARINDS.NS', name: 'Solar Industries' },
    { symbol: 'AFFLE.NS', name: 'Affle India' },
    { symbol: 'TANLA.NS', name: 'Tanla Platforms' },
    { symbol: 'MFSL.NS', name: 'Max Financial Services' },
    { symbol: 'AAVAS.NS', name: 'Aavas Financiers' },
    { symbol: 'CANFINHOME.NS', name: 'Can Fin Homes' },
    { symbol: 'HOMEFIRST.NS', name: 'Home First Finance' },
    { symbol: 'APTUS.NS', name: 'Aptus Value Housing' },
    { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance' },
    { symbol: 'PFC.NS', name: 'Power Finance Corporation' },
    { symbol: 'HUDCO.NS', name: 'HUDCO' },
    { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance' },
    { symbol: 'ABCAPITAL.NS', name: 'Aditya Birla Capital' },
    { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank' },
    { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank' },
    { symbol: 'CUB.NS', name: 'City Union Bank' },
    { symbol: 'FEDERALBNK.NS', name: 'Federal Bank' },
    { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank' },
    { symbol: 'RBLBANK.NS', name: 'RBL Bank' },
    { symbol: 'KALYANKJIL.NS', name: 'Kalyan Jewellers' },
    { symbol: 'GUJGASLTD.NS', name: 'Gujarat Gas' },
    { symbol: 'MGL.NS', name: 'Mahanagar Gas' },
    { symbol: 'IGL.NS', name: 'Indraprastha Gas' },
    { symbol: 'CONCOR.NS', name: 'Container Corporation' },
    { symbol: 'IRCON.NS', name: 'Ircon International' },
    { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam' },
    { symbol: 'RAILTEL.NS', name: 'RailTel Corporation' },
    { symbol: 'TIINDIA.NS', name: 'Tube Investments' },
    { symbol: 'SUNTV.NS', name: 'Sun TV Network' },
    { symbol: 'PVRINOX.NS', name: 'PVR INOX' },
    { symbol: 'ZEEL.NS', name: 'Zee Entertainment' },
    { symbol: 'ABFRL.NS', name: 'Aditya Birla Fashion' },
    { symbol: 'PAGEIND.NS', name: 'Page Industries' },
    { symbol: 'TTML.NS', name: 'Tata Teleservices' },
    { symbol: 'IDEA.NS', name: 'Vodafone Idea' },
    { symbol: 'JIOFIN.NS', name: 'Jio Financial Services' },
    { symbol: 'CAMS.NS', name: 'Computer Age Management Services' },
    { symbol: 'CDSL.NS', name: 'Central Depository Services' },
    { symbol: 'MCX.NS', name: 'Multi Commodity Exchange' },
    { symbol: 'BSE.NS', name: 'Bombay Stock Exchange' },
    { symbol: 'ANGELONE.NS', name: 'Angel One' },
    { symbol: 'HDFCAMC.NS', name: 'HDFC Asset Management' },
    { symbol: 'NIACL.NS', name: 'New India Assurance' },
    { symbol: 'GICRE.NS', name: 'General Insurance Corporation' },
    { symbol: 'IEX.NS', name: 'Indian Energy Exchange' },
    { symbol: 'CGPOWER.NS', name: 'CG Power and Industrial Solutions' },
    { symbol: 'SUZLON.NS', name: 'Suzlon Energy' },
    { symbol: 'TATATECH.NS', name: 'Tata Technologies' },
    { symbol: 'CUMMINSIND.NS', name: 'Cummins India' },
    { symbol: 'ABB.NS', name: 'ABB India' },
    { symbol: 'THERMAX.NS', name: 'Thermax' },
    { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics' },
    { symbol: 'CENTURYTEX.NS', name: 'Century Textiles' },
    { symbol: 'CROMPTON.NS', name: 'Crompton Greaves Consumer' },
    { symbol: 'WHIRLPOOL.NS', name: 'Whirlpool of India' },
    { symbol: 'BLUESTARLT.NS', name: 'Blue Star' },
    { symbol: 'DIXON.NS', name: 'Dixon Technologies' },
    { symbol: 'KAYNES.NS', name: 'Kaynes Technology' },
    { symbol: 'SYRMA.NS', name: 'Syrma SGS Technology' },
    { symbol: 'DATAPATTNS.NS', name: 'Data Patterns' },
    { symbol: 'COCHINSHIP.NS', name: 'Cochin Shipyard' },
    { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders' },
    { symbol: 'MAZAGONDOCK.NS', name: 'Mazagon Dock Shipbuilders' },
    { symbol: 'BDL.NS', name: 'Bharat Dynamics' },
    { symbol: 'PARAS.NS', name: 'Paras Defence' },
    { symbol: 'SOLARINDS.NS', name: 'Solar Industries' },
    { symbol: 'RAJESHEXPO.NS', name: 'Rajesh Exports' },
    { symbol: 'TITAN.NS', name: 'Titan Company' },
    { symbol: 'BATAINDIA.NS', name: 'Bata India' },
    { symbol: 'RELAXO.NS', name: 'Relaxo Footwears' },
    { symbol: 'METROBRAND.NS', name: 'Metro Brands' },
    { symbol: 'SAPPHIRE.NS', name: 'Sapphire Foods' },
    { symbol: 'DEVYANI.NS', name: 'Devyani International' },
    { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks' },
    { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld' },
    { symbol: 'VBL.NS', name: 'Varun Beverages' },
    { symbol: 'RADICO.NS', name: 'Radico Khaitan' },
    { symbol: 'UBL.NS', name: 'United Breweries' },
    { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi' },
    { symbol: 'MINDTREE.NS', name: 'LTIMindtree' },
    { symbol: 'ZENSAR.NS', name: 'Zensar Technologies' },
    { symbol: 'BIRLASOFT.NS', name: 'Birlasoft' },
    { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision' },
    { symbol: 'OLECTRA.NS', name: 'Olectra Greentech' },
    { symbol: 'EXIDEIND.NS', name: 'Exide Industries' },
    { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Energy' },
    { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India' },
    { symbol: 'SKFINDIA.NS', name: 'SKF India' },
    { symbol: 'TIMKEN.NS', name: 'Timken India' },
    { symbol: 'FIVESTAR.NS', name: 'Five Star Business Finance' },
    { symbol: 'JBCHEPHARM.NS', name: 'JB Chemicals & Pharma' },
    { symbol: 'LALPATHLAB.NS', name: 'Dr Lal PathLabs' },
    { symbol: 'METROPOLIS.NS', name: 'Metropolis Healthcare' },
    { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma' },
    { symbol: 'BIOCON.NS', name: 'Biocon' },
    { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs' },
    { symbol: 'ALKEM.NS', name: 'Alkem Laboratories' },
    { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories' },
    { symbol: 'NATCOPHAR.NS', name: 'Natco Pharma' },
    { symbol: 'GLENMARK.NS', name: 'Glenmark Pharmaceuticals' },
    { symbol: 'ABBOTINDIA.NS', name: 'Abbott India' },
    { symbol: 'SYNGENE.NS', name: 'Syngene International' },
    { symbol: 'HONAUT.NS', name: 'Honeywell Automation' },
    { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills' },
    { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises' },
    { symbol: 'PRESTIGE.NS', name: 'Prestige Estates' },
    { symbol: 'LODHA.NS', name: 'Macrotech Developers Lodha' },
    { symbol: 'SOBHA.NS', name: 'Sobha' },
    { symbol: 'SUNTECK.NS', name: 'Sunteck Realty' },
    { symbol: 'GRINFRA.NS', name: 'GR Infraprojects' },
    { symbol: 'KPIL.NS', name: 'Kalpataru Projects' },
    { symbol: 'KEC.NS', name: 'KEC International' },
    { symbol: 'ENGINERSIN.NS', name: 'Engineers India' },
    { symbol: 'NBCC.NS', name: 'NBCC India' },
    { symbol: 'NESCO.NS', name: 'Nesco' },
    { symbol: 'HINDPETRO.NS', name: 'Hindustan Petroleum' },
    { symbol: 'MRPL.NS', name: 'Mangalore Refinery' },
    { symbol: 'GSPL.NS', name: 'Gujarat State Petronet' },
    { symbol: 'TATACOMM.NS', name: 'Tata Communications' },
    { symbol: 'BAJAJELEC.NS', name: 'Bajaj Electricals' },
    { symbol: 'ORIENTELEC.NS', name: 'Orient Electric' },
    { symbol: 'KEI.NS', name: 'KEI Industries' },
    { symbol: 'HINDCOPPER.NS', name: 'Hindustan Copper' },
    { symbol: 'NATIONALUM.NS', name: 'National Aluminium' },
    { symbol: 'MOIL.NS', name: 'MOIL' },
    { symbol: 'GMRINFRA.NS', name: 'GMR Airports Infrastructure' },
    { symbol: 'ADANIENSOL.NS', name: 'Adani Energy Solutions' },
    { symbol: 'SJVN.NS', name: 'SJVN' },
    { symbol: 'NHPC.NS', name: 'NHPC' },
    { symbol: 'CESC.NS', name: 'CESC' },
    { symbol: 'JSPL.NS', name: 'Jindal Steel & Power' },
    { symbol: 'RATNAMANI.NS', name: 'Ratnamani Metals' },
    { symbol: 'AIAENG.NS', name: 'AIA Engineering' },
    { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal' },
    { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton' },
    { symbol: 'TRIDENT.NS', name: 'Trident' },
    { symbol: 'RAYMOND.NS', name: 'Raymond' },
    { symbol: 'ARVIND.NS', name: 'Arvind' },
    { symbol: 'JKCEMENT.NS', name: 'JK Cement' },
    { symbol: 'RAMCOCEM.NS', name: 'Ramco Cements' },
    { symbol: 'DALMIACEM.NS', name: 'Dalmia Bharat Cement' },
    { symbol: 'SHREECEM.NS', name: 'Shree Cement' },
    { symbol: 'ACC.NS', name: 'ACC Cement' },
    { symbol: 'STARCEMENT.NS', name: 'Star Cement' },
    { symbol: 'PRISMJOINS.NS', name: 'Prism Johnson' },
    { symbol: 'SUMICHEM.NS', name: 'Sumitomo Chemical India' },
    { symbol: 'BSOFT.NS', name: 'BFSI Software' },
    { symbol: 'INTELLECT.NS', name: 'Intellect Design Arena' },
    { symbol: 'NEWGEN.NS', name: 'Newgen Software' },
    { symbol: 'MASTEK.NS', name: 'Mastek' },
    { symbol: 'RATEGAIN.NS', name: 'RateGain Travel Technologies' },
    { symbol: 'TRIVENI.NS', name: 'Triveni Engineering' },
    { symbol: 'BALRAMCHIN.NS', name: 'Balrampur Chini Mills' },
    { symbol: 'RENUKA.NS', name: 'Shree Renuka Sugars' },
    { symbol: 'GNFC.NS', name: 'Gujarat Narmada Valley Fertilizers' },
    { symbol: 'CHAMBALFER.NS', name: 'Chambal Fertilisers' },
    { symbol: 'COROMANDEL.NS', name: 'Coromandel International' },
    { symbol: 'AARTIIND.NS', name: 'Aarti Industries' },
    { symbol: 'FINEORG.NS', name: 'Fine Organic Industries' },
    { symbol: 'GALAXYSURF.NS', name: 'Galaxy Surfactants' },
    { symbol: 'VGUARD.NS', name: 'V-Guard Industries' },
    { symbol: 'AMBER.NS', name: 'Amber Enterprises' },
    { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments' },
    { symbol: 'RITES.NS', name: 'RITES' },
    { symbol: 'HUDCO.NS', name: 'HUDCO' },
    { symbol: 'JKLAKSHMI.NS', name: 'JK Lakshmi Cement' },
    { symbol: 'CENTRALBK.NS', name: 'Central Bank of India' },
    { symbol: 'INDIANB.NS', name: 'Indian Bank' },
    { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra' },
    { symbol: 'IOB.NS', name: 'Indian Overseas Bank' },
    { symbol: 'UCOBANK.NS', name: 'UCO Bank' },
    { symbol: 'PSB.NS', name: 'Punjab & Sind Bank' },
    { symbol: 'J&KBANK.NS', name: 'Jammu & Kashmir Bank' },
    { symbol: 'SOUTHBANK.NS', name: 'South Indian Bank' },
    { symbol: 'KTKBANK.NS', name: 'Karnataka Bank' },
    { symbol: 'DCBBANK.NS', name: 'DCB Bank' },
    { symbol: 'EQUITASBNK.NS', name: 'Equitas Small Finance Bank' },
    { symbol: 'UJJIVANSFB.NS', name: 'Ujjivan Small Finance Bank' },
    { symbol: 'PNBHOUSING.NS', name: 'PNB Housing Finance' },
    { symbol: 'L&TFH.NS', name: 'L&T Finance Holdings' },
    { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings' },
    { symbol: 'SUNDARMFIN.NS', name: 'Sundaram Finance' },
    { symbol: 'ISEC.NS', name: 'ICICI Securities' },
    { symbol: 'MOTILALOFS.NS', name: 'Motilal Oswal Financial' },
    { symbol: 'IIFL.NS', name: 'IIFL Finance' },
    { symbol: 'JMFINANCIL.NS', name: 'JM Financial' },
    { symbol: 'NAM-INDIA.NS', name: 'Nippon Life India AMC' },
    { symbol: 'UTIAMC.NS', name: 'UTI Asset Management' },
    { symbol: 'MRF.NS', name: 'MRF' },
    { symbol: 'APOLLOTYRE.NS', name: 'Apollo Tyres' },
    { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries' },
    { symbol: 'CEATLTD.NS', name: 'CEAT' },
    { symbol: 'JKTYRE.NS', name: 'JK Tyre' },
    { symbol: 'ESCORTS.NS', name: 'Escorts Kubota' },
    { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland' },
    { symbol: 'FORCEMOT.NS', name: 'Force Motors' },
    { symbol: 'SWARAJENG.NS', name: 'Swaraj Engines' },
    { symbol: 'SUNDRMFAST.NS', name: 'Sundram Fasteners' },
    { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies' },
    { symbol: 'MINDA.NS', name: 'Uno Minda' },
    { symbol: 'EIHOTEL.NS', name: 'EIH Limited' },
    { symbol: 'LEMON.NS', name: 'Lemon Tree Hotels' },
    { symbol: 'CHALET.NS', name: 'Chalet Hotels' },
    { symbol: 'INDHOTEL.NS', name: 'Indian Hotels Company' },
    { symbol: 'IIFLWAM.NS', name: 'IIFL Wealth Management' },
    { symbol: 'MAZDOCK.NS', name: 'Mazagon Dock' },
    { symbol: 'POWERINDIA.NS', name: 'Hitachi Energy India' },
    { symbol: 'GPPL.NS', name: 'Gujarat Pipavav Port' },
    { symbol: 'PRINCEPIPE.NS', name: 'Prince Pipes and Fittings' },
    { symbol: 'FINOLEX.NS', name: 'Finolex Cables' },
    { symbol: 'FINPIPE.NS', name: 'Finolex Industries' },
    { symbol: 'ZENSARTECH.NS', name: 'Zensar Technologies' },
    { symbol: 'JSWINFRA.NS', name: 'JSW Infrastructure' },
    { symbol: 'CAMPUS.NS', name: 'Campus Activewear' },
    { symbol: 'GODFRYPHLP.NS', name: 'Godfrey Phillips' },
    { symbol: 'VSTIND.NS', name: 'VST Industries' },
    { symbol: 'EMAMILTD.NS', name: 'Emami' },
    { symbol: 'JYOTHYLAB.NS', name: 'Jyothy Labs' },
    { symbol: 'TATACOM.NS', name: 'Tata Communications' },
    { symbol: 'HFCL.NS', name: 'HFCL' },
    { symbol: 'STLTECH.NS', name: 'Sterlite Technologies' },
    { symbol: 'INDIAMART.NS', name: 'IndiaMART InterMESH' },
    { symbol: 'JUSTDIAL.NS', name: 'Just Dial' },
    { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite' },
    { symbol: 'FLUOROCHEM.NS', name: 'Gujarat Fluorochemicals' },
    { symbol: 'ALKYLAMINE.NS', name: 'Alkyl Amines' },
    { symbol: 'NOCIL.NS', name: 'NOCIL' },
    { symbol: 'RAIN.NS', name: 'Rain Industries' },
    { symbol: 'PCBL.NS', name: 'Phillips Carbon Black' },
    { symbol: 'SWSOLAR.NS', name: 'Sterling and Wilson Renewable Energy' },
    { symbol: 'KPIGREEN.NS', name: 'KPI Green Energy' },
    { symbol: 'IBREALEST.NS', name: 'Indiabulls Real Estate' },
    { symbol: 'MAHLIFE.NS', name: 'Mahindra Lifespace Developers' },
    { symbol: 'SIGNATURE.NS', name: 'Signatureglobal India' },
    { symbol: 'DOMS.NS', name: 'DOMS Industries' },
    { symbol: 'MANKIND.NS', name: 'Mankind Pharma' },
    { symbol: 'JBMA.NS', name: 'JBM Auto' },
    { symbol: 'CELLO.NS', name: 'Cello World' },
    { symbol: 'SAMHI.NS', name: 'Samhi Hotels' },
    { symbol: 'ANANDRATHI.NS', name: 'Anand Rathi Wealth' },
    { symbol: 'FLAIR.NS', name: 'Flair Writing' },
    { symbol: 'GPIL.NS', name: 'Godawari Power & Ispat' },
    { symbol: 'KIRLFER.NS', name: 'Kirloskar Ferrous' },
    { symbol: 'KIRLPNU.NS', name: 'Kirloskar Pneumatic' },
    { symbol: 'KIRLOSENG.NS', name: 'Kirloskar Oil Engines' },
    { symbol: 'NETWORK18.NS', name: 'Network18 Media & Investments' },
    { symbol: 'TV18BRDCST.NS', name: 'TV18 Broadcast' },
    { symbol: 'NAZARA.NS', name: 'Nazara Technologies' },
    { symbol: 'GLAND.NS', name: 'Gland Pharma' },
    { symbol: 'MEDPLUS.NS', name: 'MedPlus Health Services' },
    { symbol: 'AETHER.NS', name: 'Aether Industries' },
    { symbol: 'ANURAS.NS', name: 'Anupam Rasayan' },
    { symbol: 'SAFARI.NS', name: 'Safari Industries' },
    { symbol: 'KAYNES.NS', name: 'Kaynes Technology' },
    { symbol: 'RKFORGE.NS', name: 'Ramkrishna Forgings' },
    { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds' },
    { symbol: 'INTELLECT.NS', name: 'Intellect Design Arena' },
    { symbol: 'GOCOLORS.NS', name: 'Go Fashion' },
    { symbol: 'ETHOS.NS', name: 'Ethos' },
    { symbol: 'DBREALTY.NS', name: 'DB Realty' },
    { symbol: 'MAHSEAMLES.NS', name: 'Maharashtra Seamless' },
    { symbol: 'WELCORP.NS', name: 'Welspun Corp' },
    { symbol: 'WOCKPHARMA.NS', name: 'Wockhardt' },
    { symbol: 'LAXMIMACH.NS', name: 'Lakshmi Machine Works' },
    { symbol: 'ASTRAZEN.NS', name: 'AstraZeneca Pharma' },
    { symbol: 'PFIZER.NS', name: 'Pfizer' },
    { symbol: 'GLAXO.NS', name: 'GlaxoSmithKline Pharma' },
    { symbol: 'SANOFI.NS', name: 'Sanofi India' },
    { symbol: 'PGHH.NS', name: 'Procter & Gamble Health' },
    { symbol: 'GILLETTE.NS', name: 'Gillette India' },
    { symbol: 'MANYAVAR.NS', name: 'Vedant Fashions Manyavar' },
    { symbol: 'SAPPHIRE.NS', name: 'Sapphire Foods' },
    { symbol: 'FLUOROCHEM.NS', name: 'Gujarat Fluorochemicals' },
    { symbol: 'TATAINVEST.NS', name: 'Tata Investment Corporation' },
]

/**
 * Search the local NSE stock list by symbol or company name.
 * Returns matching entries sorted by relevance (exact symbol match first).
 */
export function searchLocalNSEStocks(query: string, limit: number = 10): NSEStockEntry[] {
    const q = query.toUpperCase().trim()
    if (!q) return []

    // Deduplicate by symbol (some entries may repeat above)
    const seen = new Set<string>()
    const uniqueStocks = NSE_STOCKS.filter(s => {
        if (seen.has(s.symbol)) return false
        seen.add(s.symbol)
        return true
    })

    // Score each stock for relevance
    const scored = uniqueStocks
        .map(s => {
            const sym = s.symbol.replace('.NS', '').replace('.BO', '')
            const name = s.name.toUpperCase()
            let score = 0

            if (sym === q) score = 100                            // exact symbol match
            else if (sym.startsWith(q)) score = 80                // symbol starts with query
            else if (sym.includes(q)) score = 60                  // symbol contains query
            else if (name === q) score = 70                       // exact name match
            else if (name.startsWith(q)) score = 50               // name starts with query
            else if (name.includes(q)) score = 40                 // name contains query
            // Also try matching individual words in the name
            else if (name.split(/\s+/).some(w => w.startsWith(q))) score = 45

            return { stock: s, score }
        })
        .filter(x => x.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)

    return scored.map(x => x.stock)
}
